nodeLinker: node-modules
packageExtensions:
  '@nrwl/linter@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/nest@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/node@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/eslint-plugin-nx@*':
    peerDependencies:
      eslint: ^8.2.0
  

