nodeLinker: node-modules
packageExtensions:
  '@nrwl/linter@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/nest@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/node@*':
    dependencies:
      typescript: ^4.5.4
  '@nrwl/eslint-plugin-nx@*':
    peerDependencies:
      eslint: ^8.2.0
  '@nrwl/cypress@*':
    dependencies:
      '@babel/core': ^7.17.8
      '@babel/preset-env': ^7.16.11
      babel-loader: ^8.2.4
      typescript: ^4.5.4
      webpack: ^5.71.0
  '@nrwl/next@*':
    dependencies:
      '@babel/core': ^7.17.8
      eslint: ^8.2.0
      next: ^12.1.0
      react: 17.0.2
      react-dom: 17.0.2
      typescript: ^4.5.4
      webpack: ^5.71.0
  '@nrwl/react@*':
    dependencies:
      eslint: ^8.2.0
  '@nrwl/storybook@*':
    dependencies:
      typescript: ^4.5.4
      webpack: ^5.71.0
  '@nrwl/web@*':
    dependencies:
      typescript: ^4.5.4
  '@yarn-tool/resolve-package@*':
    dependencies:
      '@types/node': ^17.0.23

